// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NIHR.StudyManagement.Infrastructure.Repository;

#nullable disable

namespace NIHR.StudyManagement.Infrastructure.Migrations
{
    [DbContext(typeof(StudyRegistryContext))]
    partial class StudyRegistryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("GriResearchStudyId")
                        .HasColumnType("int")
                        .HasColumnName("griResearchStudy_id");

                    b.Property<int>("ResearchInitiativeIdentifierId")
                        .HasColumnType("int")
                        .HasColumnName("researchInitiativeIdentifier_id");

                    b.Property<int>("SourceSystemId")
                        .HasColumnType("int")
                        .HasColumnName("sourceSystem_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GriResearchStudyId" }, "fk_griMapping_griResearchStudy_idx");

                    b.HasIndex(new[] { "ResearchInitiativeIdentifierId" }, "fk_griMapping_researchInitiativeIdentifier_idx");

                    b.HasIndex(new[] { "SourceSystemId" }, "fk_griMapping_sourceSystem_idx");

                    b.ToTable("griMapping", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriResearchStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Gri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gri");

                    b.Property<int>("RequestSourceSystemId")
                        .HasColumnType("int")
                        .HasColumnName("requestSourceSystem_id");

                    b.Property<int>("ResearchInitiativeId")
                        .HasColumnType("int")
                        .HasColumnName("researchInitiative_id");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("shortTitle");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResearchInitiativeId" }, "fk_griResearchStudy_researchInitiative_idx");

                    b.HasIndex(new[] { "RequestSourceSystemId" }, "fk_griResearchStudy_sourceSystem_idx");

                    b.ToTable("griResearchStudy", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriResearchStudyStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GriMappingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GriMappingId");

                    b.ToTable("griResearchStudyStatus", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("PersonTypeId")
                        .HasColumnType("int")
                        .HasColumnName("personType_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PersonTypeId" }, "fk_person_type_idx");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("family");

                    b.Property<string>("Given")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("given");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PersonId" }, "fk_personName_person_idx");

                    b.ToTable("personName", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("personRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 3, 8, 11, 9, 4, 591, DateTimeKind.Local).AddTicks(1968),
                            Description = "A Chief investigator role",
                            Type = "CHIEF_INVESTIGATOR"
                        });
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("personType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 3, 8, 11, 9, 4, 591, DateTimeKind.Local).AddTicks(2488),
                            Description = "RESEARCHER"
                        });
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.Researcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PersonId" }, "fk_researcher_person_idx");

                    b.ToTable("researcher", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int?>("ResearchInitiativeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("researchInitiativeType_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResearchInitiativeTypeId" }, "fk_researchInitiative_type_idx");

                    b.ToTable("researchInitiative", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeIdentifier", b =>
                {
                    b.Property<int>("Int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("ResearchInitiativeIdentifierTypeId")
                        .HasColumnType("int")
                        .HasColumnName("researchInitiativeIdentifierType_id");

                    b.Property<int>("SourceSystemId")
                        .HasColumnType("int")
                        .HasColumnName("sourceSystem_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("value");

                    b.HasKey("Int")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SourceSystemId" }, "fk_researchInitiativeIdentifier_sourceSystem_idx");

                    b.HasIndex(new[] { "ResearchInitiativeIdentifierTypeId" }, "fk_researchInitiativeIdentifier_type_idx");

                    b.ToTable("researchInitiativeIdentifier", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeIdentifierType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("researchInitiativeIdentifierType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 3, 8, 11, 9, 4, 592, DateTimeKind.Local).AddTicks(3764),
                            Description = "PROJECT"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 3, 8, 11, 9, 4, 592, DateTimeKind.Local).AddTicks(3824),
                            Description = "PROTOCOL"
                        });
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("researchInitiativeType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 3, 8, 11, 9, 4, 592, DateTimeKind.Local).AddTicks(4605),
                            Description = "STUDY"
                        });
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchStudyTeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("effective_to");

                    b.Property<int>("GriMappingId")
                        .HasColumnType("int")
                        .HasColumnName("griMapping_id");

                    b.Property<int>("PersonRoleId")
                        .HasColumnType("int")
                        .HasColumnName("personRole_id");

                    b.Property<int>("ResearcherId")
                        .HasColumnType("int")
                        .HasColumnName("researcher_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GriMappingId" }, "fk_researchStudyTeamMember_griResearch_idx");

                    b.HasIndex(new[] { "PersonRoleId" }, "fk_researchStudyTeamMember_personRol_idx");

                    b.HasIndex(new[] { "ResearcherId" }, "researchStudyTeamMember_researcher_idx");

                    b.ToTable("researchStudyTeamMember", (string)null);
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.SourceSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("sourceSystem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EDGE",
                            Created = new DateTime(2024, 3, 8, 11, 9, 4, 594, DateTimeKind.Local).AddTicks(4158),
                            Description = "Edge system"
                        },
                        new
                        {
                            Id = 2,
                            Code = "IRAS",
                            Created = new DateTime(2024, 3, 8, 11, 9, 4, 594, DateTimeKind.Local).AddTicks(4214),
                            Description = "IRAS system"
                        });
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriMapping", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.GriResearchStudy", "GriResearchStudy")
                        .WithMany("GriMappings")
                        .HasForeignKey("GriResearchStudyId")
                        .IsRequired()
                        .HasConstraintName("fk_griMapping_griResearchStudy");

                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeIdentifier", "ResearchInitiativeIdentifier")
                        .WithMany("GriMappings")
                        .HasForeignKey("ResearchInitiativeIdentifierId")
                        .IsRequired()
                        .HasConstraintName("fk_griMapping_researchInitiativeIdentifier");

                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.SourceSystem", "SourceSystem")
                        .WithMany("GriMappings")
                        .HasForeignKey("SourceSystemId")
                        .IsRequired()
                        .HasConstraintName("fk_griMapping_sourceSystem");

                    b.Navigation("GriResearchStudy");

                    b.Navigation("ResearchInitiativeIdentifier");

                    b.Navigation("SourceSystem");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriResearchStudy", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.SourceSystem", "RequestSourceSystem")
                        .WithMany("GriResearchStudies")
                        .HasForeignKey("RequestSourceSystemId")
                        .IsRequired()
                        .HasConstraintName("fk_griResearchStudy_sourceSystem");

                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiative", "ResearchInitiative")
                        .WithMany("GriResearchStudies")
                        .HasForeignKey("ResearchInitiativeId")
                        .IsRequired()
                        .HasConstraintName("fk_griResearchStudy_researchInitiative");

                    b.Navigation("RequestSourceSystem");

                    b.Navigation("ResearchInitiative");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriResearchStudyStatus", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.GriMapping", "GriMapping")
                        .WithMany("GriResearchStudyStatuses")
                        .HasForeignKey("GriMappingId")
                        .IsRequired()
                        .HasConstraintName("fk_griResearchStudyStatus_griMapping");

                    b.Navigation("GriMapping");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.Person", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonType", "PersonType")
                        .WithMany("People")
                        .HasForeignKey("PersonTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_person_type");

                    b.Navigation("PersonType");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonName", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.Person", "Person")
                        .WithMany("PersonNames")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("fk_personName_person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.Researcher", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.Person", "Person")
                        .WithMany("Researchers")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("fk_researcher_person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiative", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeType", "ResearchInitiativeType")
                        .WithMany("ResearchInitiatives")
                        .HasForeignKey("ResearchInitiativeTypeId")
                        .HasConstraintName("fk_researchInitiative_type");

                    b.Navigation("ResearchInitiativeType");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeIdentifier", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeIdentifierType", "ResearchInitiativeIdentifierType")
                        .WithMany("ResearchInitiativeIdentifiers")
                        .HasForeignKey("ResearchInitiativeIdentifierTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_researchInitiativeIdentifier_type");

                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.SourceSystem", "SourceSystem")
                        .WithMany("ResearchInitiativeIdentifiers")
                        .HasForeignKey("SourceSystemId")
                        .IsRequired()
                        .HasConstraintName("fk_researchInitiativeIdentifier_sourceSystem");

                    b.Navigation("ResearchInitiativeIdentifierType");

                    b.Navigation("SourceSystem");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchStudyTeamMember", b =>
                {
                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.GriResearchStudy", "GriMapping")
                        .WithMany("ResearchStudyTeamMembers")
                        .HasForeignKey("GriMappingId")
                        .IsRequired()
                        .HasConstraintName("fk_researchStudyTeamMember_griResearch");

                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonRole", "PersonRole")
                        .WithMany("ResearchStudyTeamMembers")
                        .HasForeignKey("PersonRoleId")
                        .IsRequired()
                        .HasConstraintName("fk_researchStudyTeamMember_personRol");

                    b.HasOne("NIHR.StudyManagement.Infrastructure.Repository.Models.Researcher", "Researcher")
                        .WithMany("ResearchStudyTeamMembers")
                        .HasForeignKey("ResearcherId")
                        .IsRequired()
                        .HasConstraintName("researchStudyTeamMember_researcher");

                    b.Navigation("GriMapping");

                    b.Navigation("PersonRole");

                    b.Navigation("Researcher");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriMapping", b =>
                {
                    b.Navigation("GriResearchStudyStatuses");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.GriResearchStudy", b =>
                {
                    b.Navigation("GriMappings");

                    b.Navigation("ResearchStudyTeamMembers");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.Person", b =>
                {
                    b.Navigation("PersonNames");

                    b.Navigation("Researchers");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonRole", b =>
                {
                    b.Navigation("ResearchStudyTeamMembers");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.PersonType", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.Researcher", b =>
                {
                    b.Navigation("ResearchStudyTeamMembers");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiative", b =>
                {
                    b.Navigation("GriResearchStudies");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeIdentifier", b =>
                {
                    b.Navigation("GriMappings");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeIdentifierType", b =>
                {
                    b.Navigation("ResearchInitiativeIdentifiers");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.ResearchInitiativeType", b =>
                {
                    b.Navigation("ResearchInitiatives");
                });

            modelBuilder.Entity("NIHR.StudyManagement.Infrastructure.Repository.Models.SourceSystem", b =>
                {
                    b.Navigation("GriMappings");

                    b.Navigation("GriResearchStudies");

                    b.Navigation("ResearchInitiativeIdentifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
