name: Staged Deployment
on:
  workflow_dispatch:

jobs:
  dev_build_test_deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials - All
        # if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Run Number and Build Id
        run: echo ${{ github.run_number }}-${{ github.run_id }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Install dependencies
        run: dotnet restore NIHR.StudyManagement/NIHR.StudyManagement.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore NIHR.StudyManagement/NIHR.StudyManagement.sln

      - name: Run unit tests
        run: dotnet test --no-restore --logger "console;verbosity=normal"  NIHR.StudyManagement/NIHR.StudyManagement.sln

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./NIHR.StudyManagement nihrd-lambda-dev-study-management --function-role nihrd-iam-dev-study-management-lambda-role --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name nihrd-lambda-dev-study-management --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name nihrd-lambda-dev-study-management --name main --function-version $VERSION

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: study-management-api-artifact
          path: NIHR.StudyManagement/NIHR.StudyManagement.Api/bin/Release/net6.0/publish/
        
  test_deploy:
    runs-on: ubuntu-latest
    needs: dev_build_test_deploy
    environment: TEST
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: study-management-api-artifact
          path: NIHR.StudyManagement/NIHR.StudyManagement.Api/bin/Release/net6.0/publish/

      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./NIHR.StudyManagement nihrd-lambda-test-study-management --function-role nihrd-iam-test-study-management-lambda-role --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccd-lambda-test-study-management --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccd-lambda-test-study-management --name main --function-version $VERSION

  uat_deploy:
    runs-on: ubuntu-latest
    needs: test_deploy
    environment: UAT
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: study-management-api-artifact
          path: NIHR.StudyManagement/NIHR.StudyManagement.Api/bin/Release/net6.0/publish/

      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.NIHR_STAGING_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_STAGING_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./NIHR.StudyManagement nihrs-lambda-uat-study-management --function-role nihrs-iam-uat-study-management-lambda-role --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name nihrs-lambda-uat-study-management --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name nihrs-lambda-uat-study-management --name main --function-version $VERSION

  oat_deploy:
    runs-on: ubuntu-latest
    needs: uat_deploy
    environment: OAT
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: study-management-api-artifact
          path: NIHR.StudyManagement/NIHR.StudyManagement.Api/bin/Release/net6.0/publish/

      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.NIHR_PROD_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_PROD_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./NIHR.StudyManagement nihrp-lambda-oat-study-management --function-role nihrp-iam-oat-study-management-lambda-role --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name nihrp-lambda-oat-study-management --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name nihrp-lambda-oat-study-management --name main --function-version $VERSION

  prod_deploy:
    runs-on: ubuntu-latest
    needs: oat_deploy
    environment: PROD
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: study-management-api-artifact
          path: NIHR.StudyManagement/NIHR.StudyManagement.Api/bin/Release/net6.0/publish/

      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.NIHR_PROD_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NIHR_PROD_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Add Nuget Source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./NIHR.StudyManagement nihrp-lambda-prod-study-management --function-role nihrp-iam-prod-study-management-lambda-role --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name nihrp-lambda-prod-study-management --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name nihrp-lambda-prod-study-management --name main --function-version $VERSION
          
  OAT_deploy:
    runs-on: ubuntu-latest
    needs: UAT_deploy
    environment: OAT
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: reference-data-api-artifact
          path: src/StudyApi/bin/Release/net6.0/publish/
      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add Nuget Source
        run: dotnet nuget add source --username ${{ secrets.NUGET_PACKAGE_USERNAME }} --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./src/StudyApi crnccp-lambda-oat-study-management --function-role crnccp-iam-oat-dte-role -ev "ASPNETCORE_ENVIRONMENT=Production;DTE_BUILD_STRING=OAT-${{ github.run_number }}-${{ github.run_id }};AWS_SECRET_MANAGER_SECRET_NAME=crnccp-secret-oat-study-management" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccp-lambda-oat-study-management --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccp-lambda-oat-study-management --name main --function-version $VERSION
          
  PROD_deploy:
    runs-on: ubuntu-latest
    needs: OAT_deploy
    environment: PROD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: reference-data-api-artifact
          path: src/StudyApi/bin/Release/net6.0/publish/
      - name: Configure AWS credentials - All
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CRNCC_PROD_IAM_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Add Nuget Source
        run: dotnet nuget add source --username ${{ secrets.NUGET_PACKAGE_USERNAME }} --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pa-nihr-crn/index.json"

      - name: Deploy
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./src/StudyApi crnccp-lambda-prod-study-management --function-role crnccp-iam-prod-dte-role -ev "ASPNETCORE_ENVIRONMENT=Production;DTE_BUILD_STRING=PROD-${{ github.run_number }}-${{ github.run_id }};AWS_SECRET_MANAGER_SECRET_NAME=crnccp-secret-prod-study-management" --function-publish true

      - name: Update alias to point to new version
        run: |
          VERSION=$(aws lambda list-versions-by-function --function-name crnccp-lambda-prod-study-management --query "Versions[-1]" | jq -r .Version)
          aws lambda update-alias --function-name crnccp-lambda-prod-study-management --name main --function-version $VERSION
